spring.application.name=film
tmdb.api.key=182573a804ecb1ea68ba783e0e1e2fe3
tmdb.api.url=https://api.themoviedb.org/3
tmdb.api.token="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxODI1NzNhODA0ZWNiMWVhNjhiYTc4M2UwZTFlMmZlMyIsIm5iZiI6MTc3ODM0NDA3Ny41NjksInN1YiI6IjY5ZmY2MDhkN2M4ZTFmZGRkMDMxNzA3ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.3FCUFrBCIwoz4NkUHDBSufTpCxc6UiQ3lQdpvoSAbos"
